### ISSUE TITLE
Chemlight Management

### ISSUE THREAD

**Issue by joebayles** [Esri/vehicle-commander-java#41]
The only way to remove chemlites currently is to restart the application. There should be a way to remove/adjust chemlites from within the application.

Additionally, when Vehicle Commander is being used to demo (kiosk mode), it would be nice for the chemlites and other adjustments to wipe every time.

- [x] User can modify a chemlites 
- [x] User can delete a chemlites 
- [x] User can delete all chemlites 
- [x] App can process some sort of "remove" GeoMessage that deletes all chemlites 

All of this needs to coordinate with https://github.com/Esri/squad-leader-android/issues/98.

**Comment by garys-esri** [comment]
- [ ] User can modify a chem light
- [ ] User can delete a chem light
- [x] User can delete all chem lights
- [ ] App can process some sort of "remove" GeoMessage that deletes all chem lights

All of this needs to coordinate with https://github.com/Esri/squad-leader-android/issues/98.

**Comment by csmoore** [comment]
Looks like another one that got auto-closed - reopening & please assign to whoever is verifying

**Comment by garys-esri** [comment]
@joebayles, would you like to test this? If so, I'll let you know when the release candidate builds are ready.

**Comment by joebayles** [comment]
As before, I cede "dibs" in the interest of getting it done on time, but if I can test it after Solutions pages go live next week, that'd be swell.

**Comment by csmoore** [comment]
Just a process note, you can also auto-close these after a week of being set "to verify"- we just want to give the issue originator an opportunity to test

**Comment by garys-esri** [comment]
True dat. I'll leave it open until next week.

**Comment by joebayles** [comment]
Just a process note, if you're going to auto-close it, auto-close it. If you want it tested, than have someone (not necessarily the issue originator) test it.

**Comment by csmoore** [comment]
Right as part of setting the status -to verify- assign it to the person you would like to test. If that person is unable to test, as appears to be the case here - then work together to designate an alternate.  

As part of the Asana/scrum tasks - there hopefully is a test task to group these.

**Comment by garys-esri** [comment]
Verified by @ScottCecilio
