### ISSUE TITLE
Retire Java Message Simulator

### ISSUE THREAD

**Issue by garys-esri** [Esri/vehicle-commander-java#56]
Use the Message Simulator in https://github.com/Esri/vehicle-commander-qt instead

**Comment by garys-esri** [comment]
While we're at it, maybe we should rename this repo to vehicle-commander-java.

**Comment by conklinbd** [comment]
Actually. If we are going to retire vehicle-commander-qt then we probably don't need that distinction.

**Comment by csmoore** [comment]
This was the first one we moved to Github & we didn't know the convention at that point, so adding the `-java` for consistency would be good.

Also probably implied by the original issue, but just in case, we'll just want the instructions for this repo to get updated to include where/how to get the pre-built/stand-alone (qt version of) message simulator.

**Comment by BobBooth** [comment]
Let me know if you do make the change. It will affect a few links to the repo in the Solutions Pages, I can update them.

**Comment by garys-esri** [comment]
@BobBooth, I have renamed the repo. Fortunately, GitHub is smart enough to redirect from the old URL to the new URL. But at your convenience, please replace https://github.com/Esri/vehicle-commander with https://github.com/Esri/vehicle-commander-java. Thanks!
