### ISSUE TITLE
Split built app into four downloads instead of two

### ISSUE THREAD

**Issue by garys-esri** [Esri/vehicle-commander-java#60]
We currently have two ArcGIS Online items for Vehicle Commander: [Windows 32- and 64-bit](http://www.arcgis.com/home/item.html?id=ae30551d12f443cb903f4829b03de315) and [Linux 32- and 64-bit](http://www.arcgis.com/home/item.html?id=2aa94d8f14374470a2157a3ca4e70413). To reduce download size, we would like to split these two into four:

- Windows 32-bit
- Windows 64-bit
- Linux 32-bit
- Linux 64-bit

Rather than split the current downloads, we will do this work for the next Vehicle Commander release.

We will need clear documentation in these items to say that you need a JRE of the right bittedness. For example, a 64-bit OS will not run the 32-bit app if a 32-bit JRE is not used to run the app.

We may also need the app to do some checking and logging if the wrong JRE is used. The app will start because Java is Java, but once it tries to load the ArcGIS Runtime native libraries, there will be some sort of throwable/catchable error that probably crashes the current version of the app. We need to tell the user exactly what has to be done (i.e. download and install the right JRE, or see if the computer already has the right JRE installed).

**Comment by garys-esri** [comment]
@joebayles and @jrweakland: I cut a release candidate for Windows 32-bit and Windows 64-bit. Once we agree that the app works on Windows, I will cut a release candidate for Linux 32-bit and Linux 64-bit.

**Comment by conklinbd** [comment]
@garys-esri or @joebayles or @jrweakland 
Where is the release candidate? I would like to use for my demo tomorrow and i can verify that this works.

**Comment by joebayles** [comment]
@conklinbd he has it on Box, but for the life of me I can't find the link... :angry:

**Comment by garys-esri** [comment]
I will email it to you again.

Sent from my Verizon Wireless 4G LTE DROID
On Apr 8, 2015 5:50 PM, Joe Bayles <notifications@github.com> wrote:

@conklinbd<https://github.com/conklinbd> he has it on Box, but for the life of me I can't find the link... [:angry:]

**Comment by garys-esri** [comment]
The release candidates of the binary distros are ready internally. We still need to get them posted publicly. I will push for that to happen and leave this issue assigned to me for now.

**Comment by garys-esri** [comment]
I created a Release Candidate 2 internally and will continue to push for release.

**Comment by garys-esri** [comment]
The release candidate was tested and verified. There are four downloads that will soon be posted by the release team.
