### ISSUE TITLE
New geography

### ISSUE THREAD

**Issue by garys-esri** [Esri/vehicle-commander-java#63]
Change the GPS simulation and any other spatial content to the new geography we're using for ArcGIS for the Military content.

**Comment by jrweakland** [comment]
Added to backlog: https://app.asana.com/0/23019535413946/31157540461222

**Comment by garys-esri** [comment]
I have created the new .gpx file. I still need to add it to the repo. We should also address #75.

**Comment by garys-esri** [comment]
Fixed in #76
